# Generated by Django 4.2.1 on 2023-05-22 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitassignation',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Assignee', to='authentication.hitmanprofile'),
        ),
        migrations.AddField(
            model_name='hitassignation',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Creator', to='authentication.hitmanprofile'),
        ),
    ]
